[package]
name = "longfi-sys"
version = "0.2.0"
authors = ["Marc Nijdam <marc@helium.com>", "Marc Nijdam <marc@helium.com>"]
edition = "2018"
links = "lfc"
build = "build.rs"

[build-dependencies]
cmake = "0.1"
